micro:
  enableSqlLogInterceptor:false
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
spring:
  redis:
    host: 172.16.16.157
    password: bdgroup
    port: 6379
    timeout: 0
