security:
  oauth2:
    client:
      clientId: micro-client-uac
      clientSecret: microClientSecret
      access-token-uri: http://172.16.16.169:7979/uac/oauth/token
      user-authorization-uri: http://172.16.16.169:7979/uac/oauth/authorize
    resource:
      id: micro-resource-uac
      filter-order: 3
micro:
  enableSqlLogInterceptor:false
  oauth2:
    jwtSigningKey: micro-iflytek
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
  security:
    oauth2:
      tokenStore:"jwt"
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
ribbon:
  eager-load:
    enabled: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: false
  ConnectTimeout: 60000
  ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
