management:
  security:
    enabled: false
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
spring:
  boot:
    admin:
      monitor:
        period: 60000
      discovery:
        enabled: true
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,heapdump,loggers,auditevents,hystrix.stream,activiti
